name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Go
        run: |
          go build
          mv center center-linux
          echo GO_VERSION=$(./center-linux -v | cut -d ' ' -f 3) >> $GITHUB_ENV
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: center-linux
          tag_name: v${{ env.GO_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Go
        run: |
          go build
          mv center center-macos
          echo GO_VERSION=$(./center-macos -v | cut -d ' ' -f 3) >> $GITHUB_ENV
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: center-macos
          tag_name: v${{ env.GO_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}