name: Linux

on: workflow_dispatch

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Go
        run: |
          go build
          mv center center-linux
          echo VERSION=$(./center-linux -v | cut -d ' ' -f 3) >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: center-linux
          tag_name: v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}