name: Windows

on: workflow_dispatch

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Go
        run: |
          go build
          mv center.exe center-windows.exe
          echo VERSION=$(./center-windows.exe -v | cut -d ' ' -f 3) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: center-windows.exe
          tag_name: v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}